### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#677]
- [x] ~~Review all modules and their public API and update/add where documentation is unclear/missing~~ Extracted into #897
- [x] ~~Consider using `@NonNull` and `@Nullable` annotations in public API, or through [external annotations](https://www.jetbrains.com/help/idea/external-annotations.html)~~ Given the overall non-null nature of FXGL API design, there is currently no clear benefit of this.
- [x] ~~AssetLoader.kt There have been many changes since the documentation was written. Most notably, almost all methods now do not throw any exceptions. This needs to be reflected in the docs~~ Extracted into #895 
- [x] ~~Provide a list of all engine services, so the devs know which ones to provide impl for.~~ Extracted into #896
- [x] Document implicit assumption about GameApplication.launch. The caller of GameApplication.launch must be a method in the same class that extends GameApplication. 
- [x] AnimatedTexture doc is incorrect
